#!/bin/sh

grunt build
git add dist
git commit -m "Build commit"

rand=$(date +%s)

git branch $rand
git checkout $rand
git merge develop
find * -maxdepth 0 -name 'dist' -prune -o -exec git rm -rf '{}' ';'
cp -rf dist/* .
git rm -rf dist
git rm .bowerrc .editorconfig .gitattributes .gitignore .jshintrc
git add .
git commit -m "Random Branch Commit"

git checkout master
git merge $rand
git commit -m "Merged from push commit"

git branch -D $rand
