#!/bin/sh

dt=$(date)

grunt build

git branch -D master
git branch master

git checkout master
git merge develop

find * -maxdepth 0 -name 'dist' -prune -o -exec git rm -rf '{}' ';'
git mv dist/* .
rm -rf dist
git rm -rf dist
rm .bowerrc .editorconfig .gitattributes .gitignore .jshintrc
git rm .bowerrc .editorconfig .gitattributes .gitignore .jshintrc
git add .
git commit -m "Push Commit"
git push origin master

git checkout develop
