#!/bin/sh

grunt build
git add dist
git commit -m "Build commit"

rand=$(date +%s)

git branch $rand
git checkout $rand
git merge develop
find * -maxdepth 0 -name 'dist' -prune -o -exec git rm -rf '{}' ';'
